// <auto-generated />
using HotelApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelApp.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20230723112036_seeding")]
    partial class seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelApp.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("streetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("hotels");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Country = "Jordan",
                            Name = "regency dalas",
                            Phone = 5469788,
                            city = "Amman",
                            state = "Jordan",
                            streetAddress = "#####"
                        },
                        new
                        {
                            Id = 6,
                            Country = "Jordan",
                            Name = "regency dalas",
                            Phone = 5469788,
                            city = "Amman",
                            state = "Jordan",
                            streetAddress = "#####"
                        });
                });

            modelBuilder.Entity("HotelApp.Models.HotelRoom", b =>
                {
                    b.Property<int>("hotelId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("roomId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<bool>("petFriendly")
                        .HasColumnType("bit");

                    b.Property<int>("rate")
                        .HasColumnType("int");

                    b.Property<int>("roomNumber")
                        .HasColumnType("int");

                    b.HasKey("hotelId", "roomId");

                    b.ToTable("hotelRooms");

                    b.HasData(
                        new
                        {
                            hotelId = 5,
                            roomId = 5,
                            petFriendly = true,
                            rate = 4,
                            roomNumber = 3
                        },
                        new
                        {
                            hotelId = 6,
                            roomId = 6,
                            petFriendly = false,
                            rate = 4,
                            roomNumber = 4
                        });
                });

            modelBuilder.Entity("HotelApp.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Layout")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("rooms");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Layout = 3,
                            Name = "pink"
                        },
                        new
                        {
                            Id = 6,
                            Layout = 3,
                            Name = "red"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
